name: Build CAB
on:
  push:
    tags:
      - '*'

env:
    SXSC_REPO: 'https://github.com/melo936/sxsc'

jobs: 
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git clone sxsc
        run: |
          git clone --depth=1 ${{ env.SXSC_REPO }} sxsc-src

      # Credits to echnobas, he3als, Atlas and all the contributors.
      - name: Build WinSxS packages
        run: |
          pip install -r requirements.txt | Out-Null
          $tp = .\make-cert.ps1

          New-Item -ItemType Directory -Force -Path "..\release" | Out-Null
          foreach ($file in Get-ChildItem -Path "..\" -Recurse -File -Filter "*.yaml") {
            Copy-Item -Path $file.FullName -Destination "cfg.yaml" -Force | Out-Null
            (Get-Content cfg.yaml) -replace 'version: 1.0.0.0', "version: ${{ github.ref_name }}" | Set-Content cfg.yaml -Force
            python sxsc.py
            if ($LASTEXITCODE -ne 0) { exit 1 }
            .\start-build.ps1 -Thumbprint $tp
              
            $cabFile = Get-ChildItem -Path "." -File -Filter "*.cab" | Select-Object -First 1

            $packageName = [System.IO.Path]::GetFileNameWithoutExtension($cabFile.Name)
            Copy-Item -Path "files.txt" -Destination "..\release\files_$packageName.txt" -Force | Out-Null
              
            Move-Item -Path *.cab -Destination "..\release\" -Force | Out-Null
              
            .\clean.ps1
          }
        working-directory: sxsc-src
      
  
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: release/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
